apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: load-br-netfilter-module
  labels:
    machineconfiguration.openshift.io/role: worker
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - path: /etc/modules-load.d/br_netfilter-load.conf
          mode: 0644
          overwrite: true
          contents:
            source: data:,br_netfilter
